### ISSUE TITLE
Home画面

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#12]
# Issues

- 管理画面のトップページ用のテンプレートを用意しておきたい

# Tasks

- [x] homeテンプレートを追加 #12 https://github.com/goosys/misty-bird-7370/pull/24/commits/f2d238c4230ffee7755dec7b1086fab0d3c26e6a
- [x] rspec

# Usage

```ruby
# app/controllers/admin/overview_controller.rb
module Admin
  class OverviewController < Admin::ApplicationController
    def home
    end
  end
end
```

```erb
<%# app/views/admin/overview/home.html.erb %>
<% content_for(:title) do %>
  <%= t('.title') %>
<% end %>

<% content_for(:main) do %>
  <section class="main-content__body">
    <div>Hello</div>
  </section>
<% end %>

<%= render template: 'administrate/application/home', locals: local_assigns %>
```

```yml
# config/locales/administrate.en.yml
en:
  admin:
    overview:
      home:
        title: Administrator Dashboard
```

![image](https://github.com/user-attachments/assets/c00d74fc-063c-430f-9af1-6e0374c68515)
