### ISSUE TITLE
一覧ページの上下にレコード数をカウントしたものを表示する

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#13]
# Issues

- 「全100件」のようなものを表示したい
- 下部はページャーの下
- 上部はレコードテーブルの上
  - 件数が０のときは上部は非表示

# Tasks

- [x] kaminariのpage_entries_infoが使えたので導入 #26
- [x] partial化
- [x] i18nやcssなどはアプリケーション側に任せる

# Usage

```yml
# config/locales/kaminari.ja.yml
ja:
  views:
    pagination:
      first: "&laquo; 最初"
      last: "最後 &raquo;"
      previous: "&lsaquo; 前"
      next: "次 &rsaquo;"
      truncate: "&hellip;"
  helpers:
    page_entries_info:
      one_page:
        display_entries:
          zero: "全<b>0</b>件"
          one: "全<b>1</b>件"
          other: "全<b>%{count}</b>件"
      more_pages:
        display_entries: "全<b>%{total}</b>件中 <b>%{first}</b>&nbsp;-&nbsp;<b>%{last}</b>件"
```

```scss
.resource-total-count {
  font-size: 0.9em;
  padding-top: 1.4em;
  text-align: center;
  b {
    margin-left: 0.1em;
    margin-right: 0.1em;
  }
}
p.resource-total-count:first-child {
  padding-top: 0.4em;
  padding-bottom: 0.4em;
}
```

たくさんあるとき：

![image](https://github.com/user-attachments/assets/f2649f10-7547-459c-a3c1-ffdce73cb0ac)

1ページ以内のとき：

![image](https://github.com/user-attachments/assets/9baf4ee9-a41c-40ea-b637-a99192f1dda2)

0件のとき：

![image](https://github.com/user-attachments/assets/9edde53b-210c-4101-a788-5c7a631fc352)

default_locale: :en：

![image](https://github.com/user-attachments/assets/85f6fc03-8887-4ff4-9f3c-7819e46873c9)
