### ISSUE TITLE
Field::Enumerizeのviewにスタイル用のclassを追加する

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#29]
# Issues

- 選択肢で選択したものは単純なテキスト表示ではなく、タグのような見た目にしたい

# Tasks

- [x] indexのviewにclassを追加 https://github.com/goosys/misty-bird-7370/pull/33/commits/c6c16735d9604a57a3091d9a6f4001d7ad9eae84
- [x] showにも追加

# Usage

```scss
// Enumerise Mixins
@mixin enumerize-tag {
  padding: 4px 10px;
  border-radius: 12px;
  font-size: 12px;
  transition: all $base-duration $base-timing;
  white-space: nowrap;
}
@mixin enumerize-tag-color($color) {
  color: $color;
  border: 1px solid $color;
}
@mixin enumerize-tag-color-fill($color) {
  color: $white;
  background-color: $color;
  border: 1px solid $color;
}

// Enumerise *.genre
.enumerize-tag-genre-fiction {
  @include enumerize-tag;
  @include enumerize-tag-color($red);
}
.enumerize-tag-genre-non_fiction {
  @include enumerize-tag;
  @include enumerize-tag-color($blue);
}
```

![image](https://github.com/user-attachments/assets/3811898b-fbf0-49f3-9f96-b40ffb7b1798)
![image](https://github.com/user-attachments/assets/e95921ee-2de8-4981-bd7c-bb6907bf1373)
