### ISSUE TITLE
Field::HasMany,Fiedl::NestedHasManyのindexビューを「～件」のような表示にしたい

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#6]
# Issues

- Administrateの標準だと「100 items」や「200 applications」のようにモデル名のsuffixが付くが、日本語には合わないので変えたい
- 日本語では全て「～件」となってよいと思うのでそう修正したい
- 英語では標準通りの表示になるように注意する

# Tasks

- [x] <s>日本語では全て「～件」となるように修正（とりあえず）</s> https://github.com/goosys/misty-bird-7370/pull/33/commits/a43c8339231d4ffc70ac1688652fae8142547cb8
- [x] 多言語対応である程度の対応 https://github.com/goosys/misty-bird-7370/pull/37/commits/549cae9526f47df4d4d827e91ab82bc0de1fa23d

![image](https://github.com/user-attachments/assets/c38c90bf-7e53-47db-91e6-f4e0f612f495)

![image](https://github.com/user-attachments/assets/52367246-9577-45ed-97ec-1841e3888cdb)

# Usage

```yml
en:
  activerecord:
    models:
      book: "Book"
      book_image: "Book Image"
  administrate:
    fields:
      has_many:
        pluralize: # Priority 3
          zero: ""
          one: "%{pluralize}"
          other: "%{pluralize}"
          # other: "%{count} %{model_name}"
          models:
            book_image: # Priority 2
              zero: ""
              one: "%{pluralize}"
              other: "%{pluralize}"
          attributes:
            "book/book_images": # Priority 1
              zero: ""
              one: "%{pluralize}"
              other: "%{pluralize}"
ja:
  activerecord:
    models:
      book: "書籍"
      book_image: "書籍画像"
  administrate:
    fields:
      has_many:
        pluralize: # Priority 3
          zero: ""
          other: "%{count} 件"
          # other: "%{pluralize}"
          # other: "%{count} %{model_name}"
          models:
            book_image: # Priority 2
              zero: ""
              other: "%{count} 枚"
          attributes:
            "book/book_images": # Priority 1
              zero: ""
              other: "%{count} 枚"
```
